apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  claimRef:
    namespace: default
    name: mysql-pv
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/alumno/k8s/helm/data"