apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - name: http
      port: 5000
      nodePort: 32500
      targetPort: 5000
      protocol: TCP