mysql:
  name: mysql-db
  replicaCount: 1
  containerName: mysql-db
  image:
    repository: mysql
    tag: "5.7"
  values:
    mysqlDatabase: mysql-database
    mysqlPassword: patodegoma
    mysqlUser: patito
    mysqlRootPassword: root

flaskApp:
  name: flask-app
  replicaCount: 1
  containerName: flask-app
  values:
    flaskApp: app.py
    flaskEnv: development
    flaskHost: 0.0.0.0
    mysqlUser: patito
    mysqlPassword: patodegoma
    mysqlDatabase: mysql-database